Zajęcia z programowania w TEB.

* Zajęcia 1

** Wprowadzenie

*** Beta kod

    Kod uzyskiwany po kompilacji programu java.
    Beta jest wykonywany na wirtualnej maszynie java.
    Jest to podstawowa siła języka Java. Program napisany w javie i
    skompilowany do Beta kodu może być wykonany na dowolnym komputerze
    wyposażonym w wirtualną maszynę java.

*** Instrukcje jezyka

**** Warunkowa

#+NAME: pojedyncza instrukcja warunkowa
#+BEGIN_SRC java
     if (warunek) {
     }
#+END_SRC

#+NAME: instrukcja warunkowa z alternatywa
#+BEGIN_SRC java
  if(warunek){
  } else {
  }
#+END_SRC


#+NAME: instrukcja warunkowa laczona
#+BEGIN_SRC java
  if(warunek) {
  } else if(warunek) {
  }
#+END_SRC

**** petle

#+BEGIN_SRC java
     while (warunek) {
     	program;
     }
#+END_SRC

#+BEGIN_SRC java
  for(inicjalizacja; warunek; krok) {
          program;
  }
#+END_SRC

*** Zasięg zmiennych

Każda zmienna programu jest dostępna w zdefiniowanym kontekście.
Kontekst jest nazywany zasięgiem zmiennej.

Zmienna może być widoczna w zasięgu:
- klasy 
- metody
- jawnie wydzielonym zasięgu ({})

#+NAME: zasieg zmiennych
#+BEGIN_SRC java
{

}
#+END_SRC

*** obiekt

*** Odczyt z pliku

*** Zapis do pliku

*** GUI

*** Dostęp do baz danych
**** Podstawy SQL

*** Praca w sieci
**** Wysyłanie poczty
**** Applety


** JDK (Java Software Development Kit)

* Scratch

#+BEGIN_COMMENT
#
#
#
#
#+END_COMMENT

#
# -*- mode: org; coding: utf-8-unix; -*-

